name: shellcheck

on:
  workflow_call:

jobs:
  shellcheck:
    name: 'shellcheck'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: shellcheck
        uses: bewuethr/shellcheck-action@v2
