name: shfmt

on:
  workflow_call:

jobs:
  shfmt:
    name: 'shfmt'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: shfmt
        uses: ClangBuiltLinux/actions-workflows/shfmt@main
